### ISSUE TITLE
Lists are not editable on profiles

### ISSUE THREAD

**Issue by cucumbur** [tomitm/lists#12]
This extension shows lists below every profile, but they are not editable (they have no check boxes). They are just a static bootstrap list of your Twitter lists, like how I believe it's meant to show up on your timeline.

<img width="235" alt="screenshot 2017-12-26 01 04 31" src="https://user-images.githubusercontent.com/8746469/34349892-7e517bbc-e9d9-11e7-8019-302cb51d1113.png">

lemme know if any more diagnostic info is wanted, there were a lot of errors popping up in developer tools

**Comment by tomitm** [comment]
This is somewhat intentional (not a bug), as the native UI isn't horribly inconvenient here - it's under the `[...]` menu beside the `[Follow]` button.

The checkboxes are only on the profile cards, which Twitter natively shows when you hover over a name -
 _except_ on the user's own profile (which would've been redundant normally).

Currently the sidebar lists are always the same across all pages to keep the navigation experience consistent. I could see adding a toggle to the header to add checkboxes to edit memberships, though.

I want to be careful of overloading that sidebar component. I've found the extension is used by a wide range of users, so I'm leaning towards keeping things really simple by default.

I can't really guarantee when I'll get to this, but feel free to submit a PR if you'd like. Thanks!
