### ISSUE TITLE
Cog in user pop-up

### ISSUE THREAD

**Issue by vphantom** [tomitm/lists#9]
Hi again.

Since you're already doing a great job of augmenting the user pop-up, even though it doesn't pertain to "lists" per se I figured I should share the idea here: what if we could reproduce the user "cog" menu in the pop-up? That's always been a big miss from Twitter, forcing users to load another user's entire page just to access the cog menu to, say, disable retweets. They do offer the button to [un]follow but not the cog with all the other options.

Feel free to dismiss this if it goes too far beyond the scope of your extension. I might throw it in [mine](https://github.com/vphantom/chrome-twitter-memory), but I figure what you're doing is much closer. :smiley:

**Comment by tomitm** [comment]
I agree that's annoying, but since it doesn't have much to do with lists, it's not something that belongs in this extension.

You're welcome to check out how I [augment the profile card](https://github.com/tomitm/lists/blob/master/src/profile-card.js#L62-L86) and replicate the effect in your own extension, though! 😄

**Comment by tomitm** [comment]
@vphantom Finally got around to pushing this out, sorry for the delay!

Chrome should be auto-updating you in the next 0-24 hours. 🎈
